version: "3.7"

services:
  all_test:
    image: pw_test:v2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results"
    working_dir: /usr/workspace
    environment:
      - CI=${CI}
      - BASE_URL=${BASE_URL}
      - PASSWORD=${PASSWORD}

