name: Playwright Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Запуск Playwright-тестов с Allure
        env:
          CI: ${{ secrets.CI }}
          BASE_URL: ${{ secrets.BASE_URL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          pytest --alluredir=allure-results

      - name: Get Allure history
        uses: actions/checkout@v4.2.2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action
        uses: simple-elf/allure-report-action@v1.6
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 50
        continue-on-error: true

      - name: Commit allure_report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          publish_dir: allure-history

