name: Playwright Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Запуск Playwright-тестов с Allure
        env:
          CI: ${{ secrets.CI }}
          BASE_URL: ${{ secrets.BASE_URL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          pytest --alluredir=allure-results

      - name: Сохранение Allure-отчётов
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Генерация Allure HTML-отчёта
        run: |
          pip install allure-pytest
          allure generate allure-results -o allure-report --clean

      - name: Публикация Allure-отчёта в GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          publish_dir: allure-report
